bitstream:
	vivado -mode batch -source write_bitstream.tcl
program_device:
	vivado -mode batch -source program_device.tcl
project:
	vivado -mode batch -source project.tcl
clean:
	rm -r bd NA *.jou *.log *.xml *.html .srcs
real_clean:
	rm -r output
project_clean:
	rm -r project_1 
